# -*- coding: utf-8 -*-
"""Database Manager

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TpR8AfSKTFwZoNDniVUO7-Dnfun1CYQg
"""

import os
import sqlite3
import json
from datetime import datetime
from dotenv import load_dotenv

# Supabase???좏깮???섏〈??(?놁뼱??SQLite 紐⑤뱶濡??숈옉)
try:
    from supabase import create_client, Client
    SUPABASE_AVAILABLE = True
except ImportError:
    SUPABASE_AVAILABLE = False
    Client = None  # ????뚰듃???붾?

# ?섍꼍 蹂??.env) 濡쒕뱶
load_dotenv()

class DBManager:
    """
    [DB Manager Class]
    SQLite(濡쒖뺄)? Supabase(?대씪?곕뱶)瑜??숈떆??吏?먰븯???곗씠?곕쿋?댁뒪 ?곌껐 愿由ъ옄.
    ?섍꼍 蹂?섏뿉 ?곕씪 ?먮룞?쇰줈 紐⑤뱶瑜??꾪솚?⑸땲??
    """

    def __init__(self, db_path="smishing_db.db"):
        self.mode = 'sqlite'  # 湲곕낯 紐⑤뱶: 濡쒖뺄 SQLite
        self.supabase: Client = None
        self.sqlite_path = db_path

        # 1. Supabase ?곌껐 ?쒕룄 (?대씪?곕뱶 紐⑤뱶)
        sb_url = os.getenv("SUPABASE_URL")
        sb_key = os.getenv("SUPABASE_KEY")

        if SUPABASE_AVAILABLE and sb_url and sb_key and "your-project" not in sb_url:
            try:
                self.supabase = create_client(sb_url, sb_key)
                self.mode = 'supabase'
                print(f"[System] Supabase Connected: {sb_url}")
            except Exception as e:
                print(f"[Warning] Supabase Connection Failed: {e}")
                self._init_sqlite() # ?ㅽ뙣 ??SQLite濡??대갚(Fallback)
        else:
            print("[System] Running in Local SQLite Mode")
            self._init_sqlite()

    def _init_sqlite(self):
        """
        [SQLite 珥덇린??
        濡쒖뺄 DB ?뚯씪???꾩슂???뚯씠釉붿씠 ?놁쑝硫??앹꽦?⑸땲??
        """
        self.conn = sqlite3.connect(self.sqlite_path, check_same_thread=False)
        self.cursor = self.conn.cursor()

        # 1. ?쒕굹由ъ삤(Intents) ?뚯씠釉?        # 怨듦꺽 ?좏삎怨??щ━???몃━嫄??뺣낫瑜???ν빀?덈떎.
        self.cursor.execute('''
            CREATE TABLE IF NOT EXISTS intents (
                id TEXT PRIMARY KEY,
                intent_name TEXT,
                description TEXT,
                category TEXT,
                metadata TEXT, -- JSON 臾몄옄?대줈 ???                last_updated TEXT
            )
        ''')

        # 2. 怨듦꺽 濡쒓렇(Attack Logs) ?뚯씠釉?        # ?앹꽦??怨듦꺽 臾멸뎄? 諛⑹뼱 紐⑤뜽???먯닔瑜?湲곕줉?⑸땲??
        self.cursor.execute('''
            CREATE TABLE IF NOT EXISTS attack_logs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                scenario_name TEXT,
                generated_msg TEXT,
                score REAL,
                model_used TEXT,
                timestamp TEXT
            )
        ''')

        # 3. ?먮낯 ?곗씠?곗뀑(Raw Datasets) ?뚯씠釉?        # ?숈뒿???ъ슜???먮낯 ?곗씠?곕? ??ν빀?덈떎.
        self.cursor.execute('''
            CREATE TABLE IF NOT EXISTS raw_datasets (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                source_file TEXT,
                content TEXT,
                full_json TEXT, -- JSON 臾몄옄??                ingested_at TEXT
            )
        ''')

        # 4. ?댁뒪 湲곗궗(Context) ?뚯씠釉?- [NEW]
        # 怨듦꺽 ?쒕굹由ъ삤??湲곕컲???섎뒗 ?댁뒪 ?곗씠?곕? ??ν빀?덈떎.
        self.cursor.execute('''
            CREATE TABLE IF NOT EXISTS news_articles (
                id TEXT PRIMARY KEY, -- ?댁뒪 URL ?먮뒗 怨좎쑀 ID
                news_title TEXT,
                news_content TEXT,
                source_date TEXT,
                category TEXT,
                original_json TEXT, -- ?먮낯 JSON 蹂댁〈
                saved_at TEXT
            )
        ''')

        # 5. 蹂댁븞 由ы룷??Security Reports) ?뚯씠釉?- [NEW]
        # ?앹꽦??蹂댁븞 遺꾩꽍 由ы룷?몃? ??ν빀?덈떎.
        self.cursor.execute('''
            CREATE TABLE IF NOT EXISTS security_reports (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                scenario_name TEXT,
                news_title TEXT,
                report_text TEXT, -- 留덊겕?ㅼ슫 ?띿뒪??                pdf_data BLOB, -- PDF 諛붿씠?덈━ ?곗씠??                created_at TEXT
            )
        ''')
        self.conn.commit()

    # --- Public Methods (Common Interface) ---

    def insert_log(self, log_data: dict):
        """
        [濡쒓렇 ???
        ?앹꽦???ㅻ???臾몄옄? ?먯? 寃곌낵瑜???ν빀?덈떎.
        """
        timestamp = datetime.now().isoformat()

        if self.mode == 'supabase':
            # Supabase API ?ъ슜 (JSON ?곗씠??吏곸젒 ?꾩넚)
            data = {**log_data, "timestamp": timestamp}
            self.supabase.table('attack_logs').insert(data).execute()
        else:
            # SQLite Query ?ㅽ뻾
            self.cursor.execute(
                "INSERT INTO attack_logs (scenario_name, generated_msg, score, model_used, timestamp) VALUES (?, ?, ?, ?, ?)",
                (log_data.get('scenario_name'), log_data.get('generated_msg'), log_data.get('score'), log_data.get('model_used'), timestamp)
            )
            self.conn.commit()

    def upsert_intent(self, intent_data: dict):
        """
        [?쒕굹由ъ삤 ?숆린??
        湲곗〈???덉쑝硫??낅뜲?댄듃, ?놁쑝硫??쎌엯 (Upsert)
        """
        timestamp = datetime.now().isoformat()

        if self.mode == 'supabase':
            data = {**intent_data, "last_updated": timestamp}
            self.supabase.table('intents').upsert(data).execute()
        else:
            # SQLite?먯꽌??JSON ?꾨뱶瑜?臾몄옄?대줈 蹂?섑빐????            meta_str = json.dumps(intent_data.get('metadata', {}), ensure_ascii=False)
            self.cursor.execute(
                "INSERT OR REPLACE INTO intents (id, intent_name, description, category, metadata, last_updated) VALUES (?, ?, ?, ?, ?, ?)",
                (intent_data['id'], intent_data['intent_name'], intent_data['description'], intent_data['category'], meta_str, timestamp)
            )
            self.conn.commit()

    def insert_dataset_bulk(self, data_list: list):
        """
        [????곗씠?????
        ?숈뒿 ?곗씠?곕? ??踰덉뿉 ??ν빀?덈떎. (Batch Insert)
        """
        if not data_list: return

        if self.mode == 'supabase':
            try:
                # Supabase Upsert (以묐났 諛⑹? ?ㅼ젙 ?꾩슂)
                self.supabase.table('raw_datasets').upsert(data_list, on_conflict='source_file, content').execute()
            except Exception as e:
                print(f"[DB Error] Supabase Bulk Insert Failed: {e}")
        else:
            try:
                # SQLite Executemany (怨좎냽 ?쎌엯)
                self.cursor.executemany(
                    "INSERT INTO raw_datasets (source_file, content, full_json) VALUES (:source_file, :content, :full_json)",
                    data_list
                )
                self.conn.commit()
            except Exception as e:
                print(f"[DB Error] SQLite Bulk Insert Failed: {e}")

    def insert_news(self, news_item: dict):
        """
        [?댁뒪 湲곗궗 ???
        ?щ·留곷맂 ?댁뒪 ?곗씠?곕? DB????ν빀?덈떎.
        Key: news_item['context']['url'] (?놁쑝硫?title+date ?댁떆 ?ъ슜)
        """
        if not news_item or 'context' not in news_item: return
        
        ctx = news_item['context']
        news_id = ctx.get('url', f"{ctx.get('news_title')}_{ctx.get('source_date')}")
        saved_at = datetime.now().isoformat()
        
        # ?먮낯 JSON ???        original_json = json.dumps(news_item, ensure_ascii=False)
        
        if self.mode == 'supabase':
            data = {
                "id": news_id,
                "news_title": ctx.get('news_title'),
                "news_content": ctx.get('news_content')[:], # ?꾩껜 ???                "source_date": ctx.get('source_date'),
                "category": ctx.get('category'),
                "original_json": original_json,
                "saved_at": saved_at
            }
            try:
                self.supabase.table('news_articles').upsert(data).execute()
            except Exception as e:
                print(f"[DB Error] Supabase News Insert Failed: {e}")
        else:
            try:
                self.cursor.execute(
                    """
                    INSERT OR IGNORE INTO news_articles 
                    (id, news_title, news_content, source_date, category, original_json, saved_at)
                    VALUES (?, ?, ?, ?, ?, ?, ?)
                    """,
                    (news_id, ctx.get('news_title'), ctx.get('news_content'), ctx.get('source_date'), ctx.get('category'), original_json, saved_at)
                )
                self.conn.commit()
            except Exception as e:
                print(f"[DB Error] SQLite News Insert Failed: {e}")

    def insert_report(self, report_data: dict):
        """
        [蹂댁븞 由ы룷?????
        ?앹꽦??蹂댁븞 遺꾩꽍 由ы룷?몃? DB????ν빀?덈떎.
        report_data: {
            'scenario_name': str,
            'news_title': str,
            'report_text': str (markdown),
            'pdf_data': bytes
        }
        """
        if not report_data: return
        
        created_at = datetime.now().isoformat()
        
        if self.mode == 'supabase':
            # Supabase??BLOB ???Base64 ?몄퐫???꾩슂
            import base64
            pdf_b64 = base64.b64encode(report_data.get('pdf_data', b'')).decode('utf-8') if report_data.get('pdf_data') else None
            
            data = {
                "scenario_name": report_data.get('scenario_name'),
                "news_title": report_data.get('news_title'),
                "report_text": report_data.get('report_text'),
                "pdf_data": pdf_b64,
                "created_at": created_at
            }
            try:
                self.supabase.table('security_reports').insert(data).execute()
            except Exception as e:
                print(f"[DB Error] Supabase Report Insert Failed: {e}")
        else:
            try:
                self.cursor.execute(
                    """
                    INSERT INTO security_reports 
                    (scenario_name, news_title, report_text, pdf_data, created_at)
                    VALUES (?, ?, ?, ?, ?)
                    """,
                    (
                        report_data.get('scenario_name'),
                        report_data.get('news_title'),
                        report_data.get('report_text'),
                        report_data.get('pdf_data'),  # BLOB?쇰줈 吏곸젒 ???                        created_at
                    )
                )
                self.conn.commit()
            except Exception as e:
                print(f"[DB Error] SQLite Report Insert Failed: {e}")

    def get_stats(self):
        """
        [?듦퀎 議고쉶]
        ??쒕낫?쒖뿉 ?쒖떆???곗씠??媛쒖닔瑜?諛섑솚?⑸땲??
        """
        stats = {'mode': self.mode}

        if self.mode == 'supabase':
            try:
                # count='exact', head=True: ?곗씠???놁씠 媛쒖닔留?鍮좊Ⅴ寃?議고쉶
                stats['logs'] = self.supabase.table('attack_logs').select('*', count='exact', head=True).execute().count
                stats['intents'] = self.supabase.table('intents').select('*', count='exact', head=True).execute().count
            except:
                stats['logs'] = 0
                stats['intents'] = 0
        else:
            stats['logs'] = self.cursor.execute("SELECT COUNT(*) FROM attack_logs").fetchone()[0]
            stats['intents'] = self.cursor.execute("SELECT COUNT(*) FROM intents").fetchone()[0]

        return stats

    def close(self):
        """
        [?곌껐 醫낅즺]
        SQLite ?곌껐???덉쟾?섍쾶 ?レ뒿?덈떎.
        """
        if self.mode == 'sqlite' and self.conn:
            self.conn.close()
